### ISSUE TITLE
the implementations for system-level attack gets wrong！

### ISSUE THREAD

**Issue by knight4u13** [Unispac/Subnet-Replacement-Attack#2]
$./local_SRA ../victim_model/mod_test.pkl ../attacked_model/
        argc = 3
        ori:../victim_model/mod_test.pkl 
        new:../victim_model/mod_test.pkl.txt
        the ../victim_model/mod_test.pkl rename ../victim_model/mod_test.pkl.txt
        failed! errcode:0!

I ran this code and it showed as above!

**Comment by XieJiSS** [comment]
Hi, the second argument passed to local_SRA should be an absolute path.

**Comment by XieJiSS** [comment]
Example cmdline can be found here:

https://github.com/Unispac/Subnet-Replacement-Attack/blob/0d663db00090387ccce7ea7ae749420ccffbac90/system_attacks/scenario1/local_SRA.c#L866-L869
